### ISSUE TITLE
{:ok, :undefined, :undefined}

### ISSUE THREAD

**Issue by hdcos** [r-icarus/detergentex#10]
When i launch the example request or this one : http://www.webservicex.net/New/Home/ServiceDetail/42

I get this answer from the service : {:ok, :undefined, :indefined}
Am I missing something?

here is my code:

```
Detergentex.init_model("http://www.webservicex.net/uszip.asmx?WSDL")
Detergentex.call("http://www.webservicex.net/uszip.asmx?WSDL", "GetInfoByZIP", ["35006"])
```

**Comment by mgnshawn** [comment]
I'm having the same problem. {:ok, :undefined, :undefined} from the example service in the instructions.
 wsdl_url = "http://www.webservicex.net/convertVolume.asmx?WSDL"
 action = "ChangeVolumeUnit"
 parameters = ["100", "dry", "centiliter"]
 Detergentex.call(wsdl_url, action, parameters)

**Comment by r-icarus** [comment]
@hdcos Hey I'm just trying out your code and I do get an error but it's different. 

```
{:error,
 {:decoding,
  [exception: {:error, 'Missing element before: NewDataSet'},
   stack: [:"p:GetInfoByZIPResponse/GetInfoByZIPResult",
    :"p:GetInfoByZIPResponse", :"soap:Body", :"soap:Envelope"],
   received: {:startElement, [], 'NewDataSet', [], []}]}}
```

The error here is thrown by the detergent library so there is very little I can do. Apparently the response is not what SOAP expects.

**Comment by r-icarus** [comment]
@mgnshawn I also tried the example and get this

```
{:ok, :undefined, [{:"p:ChangeVolumeUnitResponse", [], '352390.69999999995'}]}
```

So maybe the service was down for some time and now its working again ?

**Comment by mgnshawn** [comment]
@r-icarus, I tried to use detergentex against 3 different simple soap services and got the same result each time.  Someone suggested maybe it's a version issue, coils you tell me what versions of elixir and detergent are you using? I ruled out the soap services by hitting them from ruby in the same time frame.

**Comment by hdcos** [comment]
i also tried with differents framework using nodejs soap and it worked perfectly well. so I also think it comes from detergent

**Comment by alexandercg** [comment]
Alguna version en especifico de elixir para usar? o algo mas en las configuraciones del proyecto?
Me sigue dando estos resultados:

iex(4)> wsdl_url = "http://www.webservicex.net/convertVolume.asmx?WSDL"
"http://www.webservicex.net/convertVolume.asmx?WSDL"
iex(5)> action = "ChangeVolumeUnit"
"ChangeVolumeUnit"
iex(6)> parameters = ["100", "dry", "centiliter"]
["100", "dry", "centiliter"]
iex(7)> Detergentex.call(wsdl_url, action, parameters)
{:ok, :undefined, :undefined}

y estas son mis deps

  [{:earmark, "~> 0.1", only: :dev},
   {:ex_doc, "~> 0.11", only: :dev},
   {:erlsom, github: "willemdj/erlsom"},
   {:detergentex, "0.0.7"},
   {:detergent, "~> 0.3.0"}]

**Comment by r-icarus** [comment]
I'm using Elixir 1.2.2, Erlang 18.2 and detergent master. Cloned it again for this test just in case I had something else.
